replicaCount: 1

image:
  repository: mayankgajpal/kproject:flask_OCR

service:
  type: LoadBalancer
  port: 5000
  name: kproject2-service
  targetport: 5000
  nodeport: 30001

container:
  name: kproject2
  resources:
    memory: 128Mi
    cpu: 500m
