apiVersion: apps/v1
kind: Deployment
metadata:
  name: kproject1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kproject1
  template:
    metadata:
      labels:
        app: kproject1
    spec:
      containers:
      - name: kproject1
        image: mayankgajpal/kproject:django_CRUD
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
